package model;
// Generated 04-11-2016 15:47:07 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Log generated by hbm2java
 */
@Entity
@Table(name = "log", catalog = "raiting")
public class Log implements java.io.Serializable {

	private Integer id;

	private Date fechaArchivo;

	private Date fechaImportacion;
	
	private String filename;

	public Log() {
	}

	public Log(Date fechaArchivo, Date fechaImportacion) {
		this.fechaArchivo = fechaArchivo;
		this.fechaImportacion = fechaImportacion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_archivo", nullable = true, length = 0)
	public Date getFechaArchivo() {
		return this.fechaArchivo;
	}

	public void setFechaArchivo(Date fechaArchivo) {
		this.fechaArchivo = fechaArchivo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_importacion", nullable = true, length = 0)
	public Date getFechaImportacion() {
		return this.fechaImportacion;
	}

	public void setFechaImportacion(Date fechaImportacion) {
		this.fechaImportacion = fechaImportacion;
	}
	
	@Column(name = "filename", nullable = false)
	public String getFilename() {
		return this.filename;
	}
	
	public void setFilename(String filename) {
		this.filename = filename;
	}

}
