package model;
// Generated 03-11-2016 11:13:19 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MedicionCanal generated by hbm2java
 */
@Entity
@Table(name = "medicion_canal", catalog = "raiting")
public class MedicionCanal implements java.io.Serializable {

	private Integer id;

	private MedicionIndividuo medicionIndividuo;

	private int canalId;

	private int televisorId;

	private Date fechaInicio;

	private Date fechaTermino;

	public MedicionCanal() {
	}

	public MedicionCanal(MedicionIndividuo medicionIndividuo, int canalId, int televisorId, Date fechaInicio,
			Date fechaTermino) {
		this.medicionIndividuo = medicionIndividuo;
		this.canalId = canalId;
		this.televisorId = televisorId;
		this.fechaInicio = fechaInicio;
		this.fechaTermino = fechaTermino;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "medicion_individuo_id", nullable = false)
	public MedicionIndividuo getMedicionIndividuo() {
		return this.medicionIndividuo;
	}

	public void setMedicionIndividuo(MedicionIndividuo medicionIndividuo) {
		this.medicionIndividuo = medicionIndividuo;
	}

	@Column(name = "canal_id", nullable = false)
	public int getCanalId() {
		return this.canalId;
	}

	public void setCanalId(int canalId) {
		this.canalId = canalId;
	}

	@Column(name = "televisor_id", nullable = false)
	public int getTelevisorId() {
		return this.televisorId;
	}

	public void setTelevisorId(int televisorId) {
		this.televisorId = televisorId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_inicio", nullable = false, length = 0)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_termino", nullable = false, length = 0)
	public Date getFechaTermino() {
		return this.fechaTermino;
	}

	public void setFechaTermino(Date fechaTermino) {
		this.fechaTermino = fechaTermino;
	}

}
